### PR TITLE
Update main.yml

### PR DESCRIPTION
**Pull request by chebur**

### CODE REVIEW

**Comment by chebur** [comment]
@welljsjs I set up github actions to check if build.sh command finishes successfully. Looks good to me

**Comment by welljsjs** [comment]
Yeah, looks good to me, too. I'm not too experienced with GitHub workflows yet though. What do you think about setting up some other workflows for increasing the user-friendliness? Such as "Greetings, Labeler and Stale"?

**Comment by chebur** [comment]
Sure, why not.

**Comment by welljsjs** [comment]
Ok, I'll take care of that. Btw, I'm currently working on a  ZRTP integration for PJSIP. May be that sooner or later, it'll become ready for this project as well.

**Comment by chebur** [comment]
ok great

**Pull request merged**
