### PR TITLE
Pod for iOS & macOS with latest dependencies

### PR DESCRIPTION
**Pull request by welljsjs**
## Changes
- [x] pjsip 2.9
- [x] openssl 1.1.1c
- [x] opus 1.3.1
- [x] iPhone SDK 12.2, macOS SDK 10.14
- [x] libraries built for both iOS and macOS
- [x] custom OpenSSL build script
- [x] Podspec allows integration for iOS & macOS projects
- [x] no pod dependencies (is not dependent on `OpenSSL-Universal` anymore)
- [x] updated required frameworks for both iOS and macOS
- [x] iOS 9+ and macOS 10.12+ recommended (integration with native environment -> PushKit)
- [x] dropped H264 support, using native encoder and decoder ([pjsip supports the `VideoToolbox` framework starting version 2.7](https://trac.pjsip.org/repos/milestone/release-2.7))
- [x] dropping 32-bit support (?)
- [x] Created an issue template (for further bug reporting with reference to the official pjsip)
- [x] Change the Podspec to match chebur's repository
- [x] this does not ship with 32-bit compiled libraries for macOS (it still includes them for iOS though) due to Xcode 10 which doesn't come with the required build tools
- [x] openssl currently puts its header files under `include/`. This needs to be fixed to `include/openssl/`.

## Todos
- [ ] refactoring, clean up (unfortunately, I'm not really experienced in scripting - things could look way cleaner, I'll dedicate to that, help is appreciated)

Libraries for the following platforms and architectures are included: 

1. iOS
`i386 x86_64 armv7 armv7s arm64`

2. macOS
`x86_64`

For further reference, [see me old PR](https://github.com/chebur/pjsip/pull/71#issuecomment-496296127)

Solves #5

### CODE REVIEW

**Comment by chebur** [comment]
Wow that's a huge work. I'll try to review it on weekend. Also, is it possible to drop h264 support in favor of native framework?

**Comment by welljsjs** [comment]
That's already done, I forgot to add it to the list.
However, I'm still not happy with this PR as it's really messy. I'll try to clean this up asap (I'm also relying on pjsip, that's why I'm doing all this).

**Comment by chebur** [comment]
@welljsjs I was reviewing the PR and found out a typo in `openssl.sh`
Screenshot 2019-06-11 at 21 43 21

It's better to keep original file indentations and keep diff as small as possible to make it easier to track changes.

**Comment by welljsjs** [comment]
Thanks!

> It's better to keep original file indentations and keep diff as small as possible to make it easier to track changes.

Sure, you're absolutely right, that's due to my foolish VSCode extension that automatically re-indents when saving. Will solve that.

**Comment by chebur** [comment]
I rebuilt the libraries and some of the flags were reset back to previous state:
Screenshot 2019-06-11 at 22 11 27
Screenshot 2019-06-11 at 22 11 34

**Comment by chebur** [comment]
> openssl currently puts its header files under include/. This needs to be fixed to include/openssl/.
Actually, openssl headers were being included in `build/openssl/include/openssl/openssl` folder. Notice doubled `openssl/openssl` in the end.

**Comment by welljsjs** [comment]
That's nothing I was messing around with. They're set by pjsip itself. 

Did you set them manually back then?

I also don't exactly know what these settings are used for; I just stumbled over 
`#define PJ_SSL_SOCK_IMP PJ_SSL_SOCK_IMP_OPENSSL`. That's weird, as it got replaced by 
`PJ_SSL_SOCK_IMP_OPENSSL`. You sure it built successfully with OpenSSL?

Would you be so kind and attach the logs?

**Comment by chebur** [comment]
Yes. I rebuild the library with fixed openssl include path and it seems `PJ_HAS_SSL_SOCK` flag now okay. 

But the `PJMEDIA_HAS_OPENCORE_AMRNB_CODEC` flag is still `0`. I'm not sure if the absence of OpenCORE AMR-NB codec is really affecting something.

**Comment by chebur** [comment]
Overall the PR looks good. You made really good job. 

To sum up, we still have to fix: 
- openssl include path
- openssl build scripts indentation

and we will be good to go and merge it in

**Comment by welljsjs** [comment]
> I'm not sure if the absence of OpenCORE AMR-NB codec is really affecting something.

That's basically G.722.2 and I doubt anyone would make use of that.

@chebur Referring to the indentation, default is 4 spaces and I used tabs, is that what you were talking about?

**Comment by chebur** [comment]
@welljsjs I reindented openssl.sh file to make it looks closer to [original file](https://github.com/x2on/OpenSSL-for-iPhone/blob/master/build-libssl.sh)

**Comment by chebur** [comment]
Sorry, I made you wait so long. The PR was merged and podspec will soon be pushed too.

**Comment by welljsjs** [comment]
@chebur 
I don't want to wake up this PR again, this comment has a different intent; however, it seemed wrong to me to file a bug report for this, so please take this as a follow-up.

To come straight to the point: I'd be very glad to become a collaborator on this repository. 

Because I'm heavily borrowing from and relying on this repo (as an individual btw), I'd like to do my part by giving back and contributing further to this repo.
I would pay special attention to the latest bug reports in order to keep the list clean (and remove distracting issues/reports). 
Additionally, I personally think that this repo has some great potential regarding the fact that it's pretty unique out there (afaik, there're no other repos that aim to make pjsip available for literally _all_ Apple devices).

I'd be glad to hear your opinion on this (take your time).

**Comment by chebur** [comment]
Sure, you're the most concerned person so far. I appreciate your efforts on committing the PR and taking a discussion on opened issues. I agree the repo has a potential and I'd be glad to invite you to be a collaborator.

**Pull request merged**
