### PR TITLE
optional libyuv support added

### PR DESCRIPTION
**Pull request by asynnestvedt**

### CODE REVIEW

**Comment by chebur** [comment]
It seems that your precompiled binaries are compiled for arm acrhitectures only. Is there any way to comple libyuv for iOS Simulator (i386, x86_64 archs)? Can you provide your libyuv build script to include it as part of the build process?

**Comment by asynnestvedt** [comment]
The build process for libyuv for iOS is very fragile so a build script isn't very likely to work for most people. It took several days the first time around and currently isn't building on my system. If I get around to recompiling libyuv for iOS I'll include i386 & x86_64.

**Comment by nitrag** [comment]
FYI: [source](https://trac.pjsip.org/repos/wiki/Getting-Started/iPhone)

Update: since PJSIP 2.5.5, libyuv is included in the PJSIP package and configure script param --with-libyuv is removed, check ticket #1937 for more info.

Set these in your config_site.h:

#define PJ_CONFIG_IPHONE 			1
#define PJMEDIA_HAS_VIDEO			1

#include <pj/config_site_sample.h>

**Comment by welljsjs** [comment]
This should be closed, see the official docs: 

> Update: since 2.5.5, libyuv is bundled in PJSIP package and will be built and enabled automatically, see ticket #1937 for more info.

**Pull request closed without merging**
